---
title: "data analysis lab"
author: "Sami Kader-Yettefti"
format: html
---

The URL to my fork is: 

<https://github.com/kaderrsami/r-101-grade-analysis>

```{r setup1, include=FALSE}
here::i_am("r-101-grade-analysis.Rproj")

library(here)
library(vroom)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)

theme_set(theme_bw())
```

### question 1

```{r setup2}
grades <- vroom(here("grades.csv"))
```

### question 2

```{r}
exam_stats <- grades %>% 
  summarise(
            Min = min(Exam, na.rm = TRUE),
            Max = max(Exam, na.rm = TRUE),
            Median = median(Exam, na.rm = TRUE),
            Mean = mean(Exam, na.rm = TRUE))
```

```{r table1, results='asis'}
kable(exam_stats, caption = "Statistics for Exam Grades")
```

### question 3

```{r}
num_missing_exam <- grades %>%
  filter(is.na(Exam)) %>%
  summarise(Count = n()) %>%
  pull(Count)
```

A total of `r num_missing_exam` students did not take the final exam.

### question 4

```{r bar_exam_grades}
filtered_grades <- grades %>% filter(!is.na(Exam))

ggplot(filtered_grades, aes(x=Exam)) +
  geom_bar() +
  ggtitle("Bar Plot for Exam Grades") +
  xlab("Exam Grades") +
  ylab("Count")
```

